### ISSUE TITLE
Is this broken on the latest Webui?

### ISSUE THREAD

**Issue by PonyCrotTitLover** [Siberpone/lazy-pony-prompter#10]
Pressing send just hangs on "[LPP] Fetching tags: 0it [00:00, ?it/s]" or am i dumb?

**Comment by Siberpone** [comment]
Connectivity issues, most likely. Note that e621/derpi are blocked in some countries. Is the website you're trying to fetch tags from opens normally for you in a browser?

**Comment by PonyCrotTitLover** [comment]
Derpibooru, it loads fine and I know my API key works with other apps.

**Comment by PonyCrotTitLover** [comment]
nevermind. I was just being dumb and not querying anything
