### ISSUE TITLE
Prompt Format broken?

### ISSUE THREAD

**Issue by huskyhi** [Siberpone/lazy-pony-prompter#2]
I can't seem to get the drop down for prompt fromat to show anything? It stubbornly blank.
Is there a configuration step I might have missed or files I'm missing?

**Comment by Siberpone** [comment]
That's, probably, because you haven't loaded any prompts via query or prompt manager. LPP needs to know the source of the prompts in order to populate the format list, since formatters are configured separately for each source. Just send a query and they should appear.

**Comment by huskyhi** [comment]
Okay, thank you that seem to work this time. Wasn’t sure because the button seems to stay grey out on my UI for some reason.
